
project_id = "dfuawprsisgwyvdtfjvl"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]

[db]
port = 54322

[realtime]
enabled = true

[storage]
enabled = true

[auth]
enabled = true
site_url = "http://localhost:3000"

[functions.fetch-news]
verify_jwt = false

[functions.fetch-news/extract-content]
verify_jwt = false

[functions.fetch-discover]
verify_jwt = false

[functions.fetch-discover/trending]
verify_jwt = false

[functions.fetch-discover/upcoming]
verify_jwt = false

[functions.fetch-discover/recommended]
verify_jwt = false
