
project_id = "your-project-id"

[api]
enabled = false
port = 54321
schemas = ["public", "storage"]

[db]
port = 54322

[realtime]
enabled = false

[storage]
enabled = false

[functions.fetch-news]
verify_jwt = false

