// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dfuawprsisgwyvdtfjvl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRmdWF3cHJzaXNnd3l2ZHRmanZsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ1NjY5OTQsImV4cCI6MjA2MDE0Mjk5NH0.j00hL3NXcE6lTgjkn7ynBnvGS7rjBFQ_weD5aCpd4xw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);